NODES = 5

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  # Load .env file
  config.env.enable

  # Setup hostnames
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  # Setup SSH key for Ansible
  config.ssh.insert_key = false
  config.vm.provision "file", source: "~/.ssh/ansible.pub", destination: "~/.ssh/ansible.pub"
  config.vm.provision "shell", env: {ROOT_PASSWORD:ENV['ROOT_PASSWORD']}, inline: <<-SHELL
    cat /home/vagrant/.ssh/ansible.pub >> /home/vagrant/.ssh/authorized_keys
    echo "root:${ROOT_PASSWORD}" | chpasswd
  SHELL

  # Setup NODES number of nodes
  (1..NODES).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"
      node.vm.network "private_network", ip: "192.168.56.#{i+3}"
    end
  end
end
