env:
  EXECUTABLE_NAME: ""
  AUTHORIZED_FUNCTIONS: ""
  LIB_MATHS_FUNCTIONS: ""
  LIBS_TO_CHECK: ""

name: Build & Test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:

jobs:
  check-files:
    runs-on: ubuntu-latest
    continue-on-error: ${{ github.event.pull_request.base.ref != 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check useless files
        run: |
          ERR=0
          for FILE in $(find . -type f -name "*.o" -o -name "*~" -o -name "*.a" -o -name "*.gc*" -o -name "*#*#"); do
              echo "::error file=$FILE::File $FILE is not allowed"
              ERR=1
          done
          exit $ERR
  check-cleanability:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    continue-on-error: ${{ github.event.pull_request.base.ref != 'main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check cleanability
        run: |
          INIT_TREE=$(tree -a --charset=ascii)
          make all fclean
          FINAL_TREE=$(tree -a --charset=ascii)
          if [[ "$INIT_TREE" != "$FINAL_TREE" ]]; then
              echo "::error::Makefile is not cleanable"
              exit 1
          fi
  test:
    runs-on: ubuntu-latest
    container:
      image: epitechcontent/epitest-docker:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build
        run: |
          make tests_run