##
## EPITECH PROJECT, 2024
## Makefile
## File description:
## Makefile
##

ex00:
	@g++ -o ex00 ex00.cpp ../ex00/*.cpp -std=c++20 -Wall -Wextra -Werror
	@./ex00 > moi/ex00
	@diff moi/ex00 marvin/ex00 || echo "KO" && echo "OK"

ex03:
	@g++ -o ex03 ex03.cpp ../ex03/*.cpp -std=c++20 -Wall -Wextra -Werror
	@./ex03 > moi/ex03
	@diff moi/ex03 marvin/ex03 || echo "KO" && echo "OK"

ex04:
	@g++ -o ex04 ex04.cpp ../ex04/*.cpp -std=c++20 -Wall -Wextra -Werror
	@./ex04 > moi/ex04
	@diff moi/ex04 marvin/ex04 || echo "KO" && echo "OK"

ex05:
	@g++ -o ex05 ex05.cpp ../ex05/*.cpp -std=c++20 -Wall -Wextra -Werror
	@./ex05 > moi/ex05
	@diff moi/ex05 marvin/ex05 || echo "KO" && echo "OK"

ex06:
	@g++ -o ex06 ex06.cpp ../ex06/*.cpp -std=c++20 -Wall -Wextra -Werror
	@./ex06 > moi/ex06
	@diff moi/ex06 marvin/ex06 || echo "KO" && echo "OK"

.PHONY: ex00 ex03 ex04 ex06
